### ISSUE TITLE
Newer version of networkx (dependency) leads to several problem

### ISSUE THREAD

**Issue by kowac** [krishauser/GlobalRedundancyResolution#1]
Hello everyone,

I wanted to test the GlobalRedundancyResolution with a fresh system setup and installed the latest version of klampt and networkx which led to several errors:
- AttributeError: 'Graph' object has no attribute 'nodes_iter'
-> Apparently, this can be fixed by "using G.nodes()" instead of "G.nodes_iter()" as this has changed with networkx version 2.0+ (https://networkx.github.io/documentation/stable/release/release_2.0.html)
- AttributeError: 'Graph' object has no attribute 'edges_iter'
-> I assumed that the same applied for this case, changing "G.edges_iter()" to "G.edges()"
-   ... /.local/lib/python2.7/site-packages/networkx/classes/reportviews.py", line 168, in __init__
    self._nodes = graph._node
AttributeError: 'Graph' object has no attribute '_node'
-> This is where I just could not find any solution as I can't reproduce where the error might come from.

Any suggestions to get the GlobalRedundancyResolution to work?
Thank you in advance.

**Comment by kowac** [comment]
Using networkx 1.1 instead of 2.3 resolved this issue for me.

**Comment by krishauser** [comment]
Glad it was a straightforward fix. Upgrading to networkx 2.x is something I’m (slowly) working on, in addition to other new features. Please let me know if you’d like any other assistance with the package, as it may be helpful to discuss directly with me to work through the process of building and using a redundancy resolution.
